version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
      - WEBUI_SECRET_KEY=your-secret-key-change-this
      - SEARXNG_BASE_URL=http://searxng:8080
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_ENGINE=searxng
      - ENABLE_WEB_SEARCH=true
      - WEB_SEARCH_ENGINE=searxng
      - FIRECRAWL_BASE_URL=http://firecrawl:3002
      - FIRECRAWL_API_KEY=""
      - ENABLE_RAG_LOCAL_WEB_FETCH=true
      - RAG_WEB_SEARCH_DOMAIN_FILTER_ENABLED=false
      - DEFAULT_USER_ROLE=user
    volumes:
      - openwebui_data:/app/backend/data
    depends_on:
      searxng:
        condition: service_healthy
      firecrawl:
        condition: service_healthy
    networks:
      - webui_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_SECRET=your-searxng-secret-key-change-this
      - SEARXNG_HOSTNAME=localhost
    volumes:
      - ./searxng-settings.yml:/etc/searxng/settings.yml:ro
    networks:
      - webui_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

  firecrawl:
    image: python:3.11-slim
    container_name: firecrawl
    ports:
      - "3002:3002"
    volumes:
      - ./firecrawl_app.py:/app/app.py:ro
    working_dir: /app
    command: >
      bash -c "
      pip install --no-cache-dir fastapi uvicorn requests beautifulsoup4 &&
      python app.py
      "
    networks:
      - webui_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:3002/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  openwebui_data:
  searxng_config:

networks:
  webui_network:
    driver: bridge