use_default_settings: true
server:
  secret_key: your-searxng-secret-key-change-this
  bind_address: 0.0.0.0
  port: 8080
search:
  safe_search: 0
  autocomplete: google
  default_lang: en
  formats:
    - html
    - json
engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false
  - name: bing
    engine: bing
    shortcut: bi
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false
  - name: github
    engine: github
    shortcut: gh
    disabled: false